import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const frontendRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(frontendRoot, '../..');
const envFile = path.join(repoRoot, '.env');
const outputFile = path.join(frontendRoot, 'src/environments/environment.ts');

function parseEnvFile(content) {
  const vars = {};

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const separatorIndex = trimmed.indexOf('=');
    if (separatorIndex === -1) continue;

    const key = trimmed.slice(0, separatorIndex).trim();
    let value = trimmed.slice(separatorIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    value = value.replace(/;$/, '');
    vars[key] = value;
  }

  return vars;
}

const defaults = {
  API_URL: 'https://localhost:7094',
  FRONTEND_URL: 'http://localhost:4200',
};

let vars = { ...defaults };

if (fs.existsSync(envFile)) {
  vars = { ...defaults, ...parseEnvFile(fs.readFileSync(envFile, 'utf8')) };
  console.log(`[sync-env] Loaded ${envFile}`);
} else {
  console.warn(`[sync-env] No .env found at ${envFile}; using defaults`);
}

const apiUrl = vars.API_URL || vars.BACKEND_URL || defaults.API_URL;
const production = process.env.NODE_ENV === 'production';

const fileContents = `// Auto-generated by scripts/sync-env.mjs — do not edit manually.
// Source: ${path.relative(frontendRoot, envFile).replace(/\\/g, '/')}

export const environment = {
  production: ${production},
  apiUrl: '${apiUrl}',
  frontendUrl: '${vars.FRONTEND_URL || defaults.FRONTEND_URL}',
};
`;

fs.mkdirSync(path.dirname(outputFile), { recursive: true });
fs.writeFileSync(outputFile, fileContents, 'utf8');
console.log(`[sync-env] Wrote ${path.relative(frontendRoot, outputFile)} (apiUrl=${apiUrl})`);
