// Auto-generated by scripts/sync-env.mjs — do not edit manually.
// Source: ../../.env

export const environment = {
  production: false,
  apiUrl: 'https://localhost:7094/',
  frontendUrl: 'http://localhost:4200/',
};
